name: dar_elanaqa
description: Dar ElanaQa.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  image_picker: ^0.8.7+5
  flutter_spinkit: ^5.2.0
  firebase_storage: ^11.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: fonts/ElMessiri-Medium.ttf
        - asset: fonts/ElMessiri-SemiBold.ttf
          weight: 500
        - asset: fonts/ElMessiri-Bold.ttf
          weight: 700
