// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41tihWle-AJzJB5mruCk4stxHAovcF7M',
    appId: '1:327448255808:web:fb316bb926da99d9c46ea5',
    messagingSenderId: '327448255808',
    projectId: 'dar-elanaqa',
    authDomain: 'dar-elanaqa.firebaseapp.com',
    storageBucket: 'dar-elanaqa.appspot.com',
    measurementId: 'G-VXPWWZVYZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UxtY8AbTRgMrzyKSjH-Zn5mt_cJ8M5w',
    appId: '1:327448255808:android:9bd638eef39c10adc46ea5',
    messagingSenderId: '327448255808',
    projectId: 'dar-elanaqa',
    storageBucket: 'dar-elanaqa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgDrSOEhYP6of9nqOSPnMEcwFN4tz0b8',
    appId: '1:327448255808:ios:9703e3c978800f9bc46ea5',
    messagingSenderId: '327448255808',
    projectId: 'dar-elanaqa',
    storageBucket: 'dar-elanaqa.appspot.com',
    iosClientId: '327448255808-ag14lbtj8lin51imvaban8ke0k14f4k1.apps.googleusercontent.com',
    iosBundleId: 'com.example.darElanaqa',
  );
}
